# Generated by Django 5.1.7 on 2025-04-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classroom_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='classroom_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='max_distance',
            field=models.IntegerField(default=50),
        ),
    ]
